export const FETCH_SPACEX = 'FETCH_SPACEX';
export const FETCH_LAUNCH_SPACEX = 'FETCH_LAUNCH_SPACEX';
export const FETCH_LAND_SPACEX = 'FETCH_LAND_SPACEX';
export const FETCH_LAUNCH_YEAR_SPACEX = 'FETCH_LAUNCH_YEAR_SPACEX';
export const SPACEX_ERROR = 'SPACEX_ERROR';